### PR TITLE
Allow for resource to be nil when broadcasting a collection

### PR DESCRIPTION
**Pull request by adampal**
* If you have a `has_many optional: true` relationship the resource
  may not exist.  Prior to this change, the broadcast for all resources
  would fail if any of them were optional and didn't exist on the
  parent.

### CODE REVIEW

**Comment by julianrubisch** [comment]
@adampal I'm having a bit of a hard time grokking what you mean, given that I don't know a `has_many optional:true`, only a `belongs_to optional: true`

With my latest refactoring the implementation has changed a bit, and I want to help. I've put up a test case here:

https://github.com/leastbad/cable_ready/pull/16/files

but can't get it to fail. Could you take a look at this? Thanks 🙏

**Comment by adampal** [comment]
@julianrubisch sorry, that was a typo in my PR.  It should have said `belongs_to optional: true`.
Thanks for adding the test case.  Let me check it out and see if I can replicate the issue I was seeing in the app I was working on.

**Comment by julianrubisch** [comment]
That would be awesome, thanks! Sorry for the inconvenience, I think it makes sense to have that properly backed by a test.

**Comment by leastbad** [comment]
@adampal are you on Discord? If not, please consider joining the discussion about this PR.

https://discord.gg/stimulus-reflex

https://discordapp.com/channels/629472241427415060/876769348327452673/889449579878154290

**Comment by erlingur** [comment]
@julianrubisch I commented on your PR with a "fix" to make it fail :)

**Comment by julianrubisch** [comment]
Thanks all! Fixed in #16

**Comment by leastbad** [comment]
Great work, team. Thanks for the contribution, @adampal!

**Comment by adampal** [comment]
Thanks everyone. Glad we got it resolved so easily!

**Pull request closed without merging**
